#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= lowlevel_init.o
obj-y 	+= movi.o
obj-n	+= debug_led.o
obj-y	+= tq2440.o
